services:
  downloader:
    user: "1000:1000"
    image: alpine:3.19.1
    volumes:
      - ${APP_DATA_DIR}/data/nerva:/data/nerva
      - ${APP_DATA_DIR}/download.sh:/download.sh
    command: >
      sh -c "
      wget -O /data/nerva/p2pstate.nerva.v11.bin https://github.com/nerva-project/nerva/releases/download/v0.2.1.0/p2pstate.nerva.v11.bin;
      wget -O /data/nerva/quicksync.raw https://github.com/nerva-project/nerva/releases/download/v0.2.1.0/quicksync.raw;
      "
  
  nervad:
    user: "1000:1000"
    restart: unless-stopped
    image: sn1f3rt/nerva:v0.2.1.0
    depends_on:
      downloader:
        condition: service_completed_successfully
    ports:
      - "17565:17565"
      - "17566:17566"
    volumes:
      - ${APP_DATA_DIR}/data/nerva:/data/nerva
      - ${APP_DATA_DIR}/start.sh:/start.sh:ro
    command: 
      - start.sh

  app_proxy:
    environment:
      APP_HOST: vadrigar-nerva_web_1
      APP_PORT: 80

  web:
    image: nginx:1.24.0-alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/app:/usr/share/nginx/html:ro
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nervad
  
  api:
    image: node:18.19.0-alpine
    user: "root"
    working_dir: /app
    volumes:
      - ${APP_DATA_DIR}/api:/app
      - ${APP_DATA_DIR}/data/nerva:/data/nerva
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "npm install express && node server.js"
    depends_on:
      - web